image: ruby:2.1
services:
  - postgres:9.3
before_script:
  - apt-get update
  - apt-get install -y nodejs
  - gem install bundler
  - bundle install --without production
  - rake db:setup
rspec:
  script: rake spec
  type: test
  tags:
    - ruby
    - postgres
